name: master_ifab
description: "Mi primera App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^14.0.1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  pie_chart: ^5.4.0
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  video_player: ^2.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/icon/
